---
new_page_extension: md
auto_deploy: false
admin_path: "/admin/"
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: _trainers
  label: Trainers
  create: all
  match: "**/*"
  templates:
  - trainer
- type: directory
  path: _services
  label: Services
  create: all
  match: "**/*"
  templates:
  - service
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: directory
  path: _pages
  label: Pages
  create: all
  match: "**/*"
  templates:
  - page
- type: heading
  label: Data
- type: document
  path: _data/contact.yml
  label: Contact
- type: document
  path: _data/testimonials.yml
  label: Testimonials
  templates:
  - testimonials
upload_dir: assets/uploads
public_path: "/assets/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
